name: Limit complexity

on:
  pull_request:
  push:
    branches: [ master ]
    paths-ignore: [ docs/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3 SenderModule/*.cpp Lib/*.cpp -x"./Lib/catch.hpp"