name: Limit complexity

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity Sender
      run: $HOME/.local/bin/lizard ./sender/ --CCN 3 -x"./catch.hpp"
    
    - name: Limit complexity Receiver
      run: $HOME/.local/bin/lizard ./receiver/ --CCN 3 -x"./catch.hpp"