name: Main Workflow

on:
  pull_request:
  push:
    branches: [ master ]
    paths-ignore: [ docs/*, includes ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build sender
      run: g++ -Wall -Wextra -Werror -o sender-executable sender.cpp
    
    - name: build receiver
      run: g++ -Wall -Wextra -Werror -o receiver-executable receiver.cpp 
    
    - name: run sensor emulator
      run: ./sender-executable | ./receiver-executable