name: Main Workflow

on:
  pull_request:
  push:
    branches: [ master ]
    paths-ignore: [ docs/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build sender
      run: g++ -Wall -Wextra -Werror -o sender-executable sender.cpp SenderModule/CSVReader.cpp SenderModule/Timer.cpp Lib/DataProcessingUtility.cpp
    
    - name: run sender-executable
      run: ./sender-executable
