name: Build and Run

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build sender
      run: g++ -Wall -Wextra -o testchecker sender/*.cpp

    - name: run sender
      run: ./testchecker

    - name: build receiver
      run: g++ -Wall -Wextra -o testchecker receiver/*.cpp

    - name: run receiver
      run: ./testchecker
      
