name: Build and Run Unit Tests

on:
  pull_request:
  push:
    branches: [ master ]
    paths-ignore: [ docs/*, includes ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
    
    - name: static analysis (sender)
      run: cppcheck --enable=all --error-exitcode=1 --suppress='*:includes*' ./sender/*.cpp 
      
    - name: build sender
      run: g++ -Wall -Wextra -Werror --coverage -o sender/testchecker sender/*.cpp
      
    - name: run sender
      run: ./testchecker
    
    - name: sender coverage report
      run: gcov -r *.cpp
    
    - name: clean sender .gcno files
      run: rm *.gcno

    - name: static analysis (sender)
      run: cppcheck --enable=all --error-exitcode=1 --suppress='*:includes*' ./receiver/*.cpp 

    - name: build receiver
      run: g++ -Wall -Wextra -Werror --coverage -o receiver/testchecker receiver/*.cpp
      
    - name: run receiver
      run: ./testchecker
    
    - name: receiver coverage report
      run: gcov -r *.cpp